global.minigameResults = [4,4,4,4];
offset = irandom_range(0, 32) + 16;
player_one_grab.visible = false;
player_two_grab.visible = false;
player_three_grab.visible = false;
player_four_grab.visible = false;
global.localPlayers[0].visible = false; // bugfix!!!
global.localPlayers[1].visible = false;
global.localPlayers[2].visible = false;
global.localPlayers[3].visible = false;
pos = 1;
final = 3;
/*player_one_SSS.player = 0;
player_two_SSS.player = 1;
player_one_SSS.player = 2;
player_one_SSS.player = 3;
player_one_SSS.index = global.playerOneIndex;
player_two_SSS.index = global.playerTwoIndex;
player_three_SSS.index = global.playerThreeIndex;
player_four_SSS.index = global.playerFourIndex; // default setup*/

alarm[2] = 60*60;